<a href="https://colab.research.google.com/github/Giovanni-Hessel/FIAP-ML-2026/blob/main/CHECKPOINT_1_%E2%80%93_Machine_Learning_%26_Statistical_Computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# CHECKPOINT 1 – Machine Learning & Statistical Computing
* Turma: 1TIAPZ-2026 (1º semestre)

* Prepare os dados, separe conjuntos de treino e teste e treine o modelo KNN apresentado em aula.
* Treine o modelo KNN testando diferentes valores de k (por exemplo: k = 1, 3, 5, 7, 9).
* Para cada valor de k, realize a predição no conjunto de teste e calcule a métrica acurácia. Apresente os
resultados em tabela comparativa.

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [9]:
from sklearn.datasets import load_iris
iris = load_iris()
# iris

In [10]:
#Adiciaonado os nomes das colunas dos respectivos dados.
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df["target"] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
#Mostrando os valores de target com os respequitivos nomes
df_especies = pd.DataFrame([sorted(df['target'].unique())], columns=iris.target_names)
df_especies.head()

   setosa  versicolor  virginica
0       0           1          2

In [ ]:
#metadados do dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [13]:
#descrendo os dados
#sepal = sépala
#Petal = pétala
#Lenght = Comprimento
#width = Largura
df.drop(columns = ['target']).describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [32]:
#Preparando os dados e separando teste e treino
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
#Treinando com os valores 1,3,5,7,9 fr k.
#Prevendo com os dados que separamos pra teste.
ks  = [1,3,5,7,9]
mls_knn_classifier = []
preds_knn_classifier = []

for k in ks:
  id = "Uniform-K" + str(k)
  ml_knn_classifier = KNeighborsClassifier(n_neighbors = k , weights = 'uniform')
  ml_knn_classifier.fit(X_train, y_train) #treinando
  pred_knn_classifier = ml_knn_classifier.predict(X_test) #testando

  mls_knn_classifier.append({"id": id, 'modelo': ml_knn_classifier}) #modelo treinado
  preds_knn_classifier.append({"id": id, 'modelo': pred_knn_classifier}) #resultado do teste

  id = "Distance-K" + str(k)
  ml_knn_classifier = KNeighborsClassifier(n_neighbors = k , weights = 'distance')
  ml_knn_classifier.fit(X_train, y_train) #treinando
  pred_knn_classifier = ml_knn_classifier.predict(X_test) #testando

  mls_knn_classifier.append({"id": id, 'modelo': ml_knn_classifier}) #modelo treinado
  preds_knn_classifier.append({"id": id, 'modelo': pred_knn_classifier}) #resultado do teste

In [44]:
#Calculando a acuracia
from sklearn.metrics import accuracy_score

laccuracy = []

for pred in sorted(preds_knn_classifier, key=lambda x: x['id']):
  laccuracy.append({
            "id" : pred['id']
            ,"Modelo" : f"KNN Classifier {pred['id']}"
            ,'Qtde_Erros' : int(np.sum(y_test != pred['modelo']))
            ,"Acuracia" : round(accuracy_score(y_test, pred['modelo']),4)
})

df_accuracy = pd.DataFrame(laccuracy)
df_accuracy.head(30)

            id                      Modelo  Qtde_Erros  Acuracia
0  Distance-K1  KNN Classifier Distance-K1           0    1.0000
1  Distance-K3  KNN Classifier Distance-K3           0    1.0000
2  Distance-K5  KNN Classifier Distance-K5           0    1.0000
3  Distance-K7  KNN Classifier Distance-K7           0    1.0000
4  Distance-K9  KNN Classifier Distance-K9           0    1.0000
5   Uniform-K1   KNN Classifier Uniform-K1           0    1.0000
6   Uniform-K3   KNN Classifier Uniform-K3           0    1.0000
7   Uniform-K5   KNN Classifier Uniform-K5           0    1.0000
8   Uniform-K7   KNN Classifier Uniform-K7           1    0.9667
9   Uniform-K9   KNN Classifier Uniform-K9           0    1.0000